package com.africancooking.backend.model;

public enum Kitchen {
    AFGHAN, AFRICAN, AMERICAN, APULIAN, ARABIC, ARGENTINIAN, ASIAN, ASSYRIAN, CUISINE, AUSTRALIAN, CURRY, BAR, BARBECUE, BASQUE, BEER, RESTAURANTS, BRAZILIAN, COFFEE_SHOP, CHILEAN, CHINESE, DELI, GERMAN, EUROPEAN, FAST, FOOD, FRENCH, FUSION, BREWERY, HEALTHY, GREEK, GRILLED, SPECIALTIES, HAWAIIAN, INDIAN, INDONESIAN, INTERNATIONAL, ISRAELI, ITALIAN, JAMAICAN, JAPANESE, CANADIAN, CARIBBEAN, KOREAN, CROATIAN, LATIN, LEBANESE, MOROCCAN, MEDITERRANEAN, SEAFOOD, MEXICAN, MONGOLIAN, NEAPOLITAN, NORTHERN, ORIENTAL, EASTERN, PAKISTANI, PERSIAN, PERUVIAN, PIZZA, POLISH, PORTUGUESE, PUB, RESTAURANT, BARS, ROMANIAN, RUSSIAN, ROMAN, SHANGHAI, SWISS, SICILIAN, SPANISH, EATERY, SRI, LANKAN, SWEETS, STALL, STEAKHOUSE, STREET, SOUPS, SUSHI, SZECHUAN, SOUTH, SOUTHERN, THAI, TUSCAN, TUNISIAN, TURKISH, HUNGARIAN, VIETNAMESE, WINE, BARS_AND_WINE, TAVERNS, CONTEMPORARY, CENTRAL, ETHIOPIAN, AUSTRIAN
}
